language: python
python:
  - "2.7"
  - "3.4"

install:
  - pip install sphinx sphinx_rtd_theme coverage codacy-coverage
  - pip install -r requirements.txt

script:
  - python setup.py install
  - PYTHONPATH=src coverage run `which pytest`
  - coverage debug data
  - coverage xml --include "src/scitokens/*"

after_success:
  - pushd docs
  - if [ "${TRAVIS_PYTHON_VERSION}" == "2.7" ]; then make gh-pages; fi
  - popd
  - if [ "${TRAVIS_PYTHON_VERSION}" == "2.7" -a "${TRAVIS_PULL_REQUEST}" = "false" ]; then python-codacy-coverage -r coverage.xml; fi

